name: Update Clash Rules from URL

on:
  push: # 可选：当有代码推送到仓库时触发
  schedule: # 可选：每天定时触发（例如，每天凌晨 3 点 UTC）
    - cron: '0 3 * * *'
  workflow_dispatch: # 可选：允许手动触发

permissions:
  contents: write

jobs:
  generate_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requirements
      run: pip install requests && pip install requests pyyaml

    - name: Fetch Data from URL
      id: fetch_data
      run: |
        DATA_URL="https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/AiDomain.list"
        RAW_DATA=$(curl -s "$DATA_URL")
        echo "RAW_DATA<<EOF" >> $GITHUB_OUTPUT
        echo "$RAW_DATA" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Process Data and Generate Rules
      env:
        RAW_DATA: ${{ steps.fetch_data.outputs.RAW_DATA }}
      run: python process_rules.py

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated update of domain and IP lists from URL"
        push_options: '--force'